travis:
  secure:
    BINSTAR_TOKEN: VB6yZwoM2thk6bqrKawgXmMqv1/nvN3IPAZAp6iLaVBnryKGMsMbFbucRy8ZPC7sFre/RyFf61x4h29G4VcXLBIOQmzp9hbw2G0dMYTsPZK7YZaGv8H+1M0JJloA3zxqk65Y26JoixKtGxXRdwfKGXAWHsOD7huFGRCoK4crWQlm2dlkPJ3Nu9UG446PPuZSNSZUK2NSv2qG7wXCiRPjm3RmyM8hxpYz8REsR9WjbYWuvLvUbyvGUt2MW+OlAT2ahGrMmAH7Erq3CE0Nv4Yz+Hf4ie17rs+P+AM2yRHHs4sQc9x27jG+ut28LR32VwKHa47Vj1Anfo6nVtrvy/SViJu2xozNNs3orF9zGt1Pi05SKWNgaqXVibp2ChEoQC0MR9jsna4YbEU4sAuEPd/N5d55PD8jKx75j1LPG3KhhSdVUzyyUJNQUr/AYk5yOZG8notSPsks639ieZitMGkO53hEx3jgK6LcXD1kVV9Hbg3Rnsx2s/oY/J3Ql5ujfzhbPKjvIpvhSJlCYY9VIK6P4Cq/0rag+312TR7N1L3JkvvzvEW7Er0EmOGFzTF6pk1cKT+2NtqEYp5sdIjbZ9F+9bi3G1ITAjyYu4/L+JS+7GDqmbXOb1qRLPu6i+ON39X8j8HrcQ3leXy460lI5MY82bOLdGKfLm1uLYqz86WE96Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
